version: '3.5'

services:
  mosquitto:
    container_name: mos-tls
    image: eclipse-mosquitto:latest
    volumes:
      - ./config:/mosquitto/config/
    ports:
      - '8883:8883'
    networks:
      - default
    restart: unless-stopped

networks:
  default:
