version: '3.5'

services:
  mosquitto:
    container_name: mos-bruteforce
    image: eclipse-mosquitto:latest
    volumes:
      - ./config:/mosquitto/config/
    ports:
      - '1883:1883'
    networks:
      - default
    restart: unless-stopped

networks:
  default:
