version: '3.5'

services:
  mosquitto:
    container_name: mos-Setup
    image: eclipse-mosquitto:latest
    volumes:
      - ./config:/mosquitto/config
      - ./log:/mosquitto/log
      - ./data:/mosquitto/data
    ports:
      - '1883:1883'
    networks:
      - default
    restart: unless-stopped

networks:
  default:
